# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-09-17 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('form_name', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('fb_url', models.URLField(blank=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=1000)),
                ('description', djangocms_text_ckeditor.fields.HTMLField()),
                ('thank_you_text', djangocms_text_ckeditor.fields.HTMLField()),
                ('backup', models.BooleanField(default=True, verbose_name='Accept backup seats?')),
                ('hide', models.BooleanField(default=False, verbose_name='Hide event from listing')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(max_length=50)),
                ('attendee_email', models.CharField(blank=True, max_length=50)),
                ('attendee_phone', models.CharField(blank=True, max_length=50)),
                ('attendee_gender', models.CharField(blank=True, max_length=50)),
                ('attendee_details', models.CharField(blank=True, max_length=500)),
                ('isbackup', models.BooleanField(default=False, verbose_name='Is a backup?')),
                ('registration_date', models.DateTimeField()),
                ('haspaid', models.BooleanField(default=False, verbose_name='Has paid?')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmo_app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('method', models.CharField(choices=[('Tilisiirto', 'Tilisiirto'), ('Käteinen', 'Käteinen'), ('Ilmainen', 'Ilmainen'), ('Muu', 'Muu')], max_length=100)),
                ('receiver', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.PositiveIntegerField(blank=True, null=True)),
                ('due_to', models.DateField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=100, null=True)),
                ('special_price_offsets', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ilmo_app.Payment'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmo_app.Place'),
        ),
    ]