# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url_alias', models.CharField(max_length=50)),
                ('json_content', models.CharField(max_length=4096)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='form_name',
        ),
        migrations.AddField(
            model_name='event',
            name='form',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ilmo_app.EventForm'),
            preserve_default=False,
        ),
    ]
