# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ilmo_app', '0002_auto_20181110_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url_alias',
            field=models.CharField(default='eventform', max_length=50),
            preserve_default=False,
        ),
        migrations.RunSQL("""
                          UPDATE ilmo_app_event
                          SET url_alias = 
                          (
                          SELECT url_alias FROM ilmo_app_eventform
                          WHERE ilmo_app_event.form_id = ilmo_app_eventform.id
                          )
                          """),
        migrations.RemoveField(
            model_name='eventform',
            name='url_alias',
        )
    ]
