# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmo_app', '0002_auto_20181110_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ilmo_app.EventForm'),
        ),
    ]
