# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ilmo_app', '0003_auto_20181113_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='open_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 1, 0, 0), null=True, verbose_name='Lomakkeen alkamisaika'),
        ),
        migrations.AlterField(
            model_name='event',
            name='backup',
            field=models.BooleanField(default=True, verbose_name='Tapahtumaan voi osallistua varasijalle?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Osallistujien enimmäismäärä'),
        ),
        migrations.AlterField(
            model_name='event',
            name='close_date',
            field=models.DateTimeField(verbose_name='Lomakkeen sulkemisaika'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Tapahtumakuvaus'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name='Tapahtuman ajankohta'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fb_url',
            field=models.URLField(blank=True, verbose_name='Linkki Facebook-tapahtumaan'),
        ),
        migrations.AlterField(
            model_name='event',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ilmo_app.EventForm', verbose_name='Lomake'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Piilota tapahtuma listauksesta?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Linkki otsakekuvaan'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tapahtuman nimi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ilmo_app.Payment', verbose_name='Maksutapa'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilmo_app.Place', verbose_name='Tapahtuman paikka'),
        ),
        migrations.AlterField(
            model_name='event',
            name='thank_you_text',
            field=djangocms_text_ckeditor.fields.HTMLField(verbose_name='Teksti, joka näytetään lomakkeen lähettämisen jälkeen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url_alias',
            field=models.CharField(max_length=50, unique=True, verbose_name='URL-nimi'),
        ),
    ]
