# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmo_app', '0005_auto_20190304_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_hhmm',
            field=models.BooleanField(default=True, verbose_name='Näytä tt:mm'),
        ),
    ]
