# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-10 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmo_app', '0005_auto_20190304_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ilmo_app.EventForm', verbose_name='Lomake'),
        ),
        migrations.AlterField(
            model_name='event',
            name='open_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 10, 22, 38, 12, 562325), null=True, verbose_name='Lomakkeen alkamisaika'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ilmo_app.Payment', verbose_name='Maksutapa'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ilmo_app.Place', verbose_name='Tapahtuman paikka'),
        ),
        migrations.AlterField(
            model_name='eventform',
            name='json_content',
            field=models.CharField(max_length=4096, verbose_name='JSON content'),
        ),
        migrations.AlterField(
            model_name='eventform',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Form name'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_to',
            field=models.DateField(blank=True, null=True, verbose_name='Due to date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Tilisiirto', 'Tilisiirto'), ('Käteinen', 'Käteinen'), ('Ilmainen', 'Ilmainen'), ('Muu', 'Muu')], max_length=50, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Payment name'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receiver',
            field=models.CharField(blank=True, max_length=50, verbose_name='Beneficiary'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Reference number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='special_price_offsets',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Price offsets'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Zip code'),
        ),
    ]
