# Generated by Django 2.1.13 on 2019-10-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmo_app', '0005_auto_20190304_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ilmo_app.EventForm', verbose_name='Lomake'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ilmo_app.Payment', verbose_name='Maksutapa'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ilmo_app.Place', verbose_name='Tapahtuman paikka'),
        ),
    ]
